### ISSUE TITLE
apex installation error

### ISSUE THREAD

**Issue by qianlou** [sacmehta/delight#7]
Hi delight authors,

I am using a Linux system with **cuda=10.1, pytorch=1.5.0** to reproduce your great work. 
I encountered an error when I run the following command:

`pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext"   --global-option="--deprecated_fused_adam" --global-option="--xentropy"   --global-option="--fast_multihead_attn" ./`

The error seems that ATen is not found:

```
    In file included from apex/contrib/csrc/multihead_attn/additive_masked_softmax_dropout_cuda.cu:14:0:
    apex/contrib/csrc/multihead_attn/softmax.h:2:10: fatal error: ATen/CUDAGeneratorImpl.h: No such file or directory
     #include <ATen/CUDAGeneratorImpl.h>
              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command '/home/qian/anaconda3/envs/home/pkgs/cuda-toolkit/bin/nvcc' failed with exit status 1
    Running setup.py install for apex ... error
ERROR: Command errored out with exit status 1: /home/qian/anaconda3/envs/home/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ioaif4t7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ioaif4t7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext --deprecated_fused_adam --xentropy --fast_multihead_attn install --record /tmp/pip-record-2v5qna5p/install-record.txt --single-version-externally-managed --compile --install-headers /home/qian/anaconda3/envs/home/include/python3.8/apex Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/qian/anaconda3/envs/home/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 812, in install
    success = install_legacy(
  File "/home/qian/anaconda3/envs/home/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure
```

Did you meet similar issues? Thanks very much for any response!

**Comment by sacmehta** [comment]
Apex is only useful for Transformer models. You can skip it for DeLighT.
